language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: TxJL7wTpkfXvB/0ietdBa0w4Qz1U6li7YVdUsPBxxezzYPqGJKPK9WDZ+eu8x1l0UrJcljfKvf4cPbqsFXtqgE1uhCBJ5h4BmPsE6MKwZcQdZNoRgjVMCVMq9vPimYhKzll2QTapyNBxAKkeD2JofA3nKXn+GdRLrbPkUuLvjZI=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: HBUYGYVm72UCCbFKzm/CBz+ZBk3sej1b5F+Hnw0daMpPzTDdTx8T6mAs1ChQMISG6PrJ9Qk9iu4+hx/VbUN5xsbYnM4Gs7vUPPRw0RnHxcKdqVOIPlk4/43PAUv6KtPx2WHhl+HsC7H/Q+MCuv978HDkPnA3zhndBXa/XEHbfyA=
sudo: false
